### ISSUE TITLE
ValueError: no signature found for builtin function <built-in function issubclass>

### ISSUE THREAD

**Issue by smarie** [aliles/funcsigs#34]
```python
from funcsigs import signature
from functools import partial
f = partial(issubclass, bool)
signature(f)
```

yields

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Miniconda3\envs\tools_py2\lib\site-packages\funcsigs\__init__.py", line 108, in signature
    sig = signature(obj.func)
  File "C:\Miniconda3\envs\tools_py2\lib\site-packages\funcsigs\__init__.py", line 185, in signature
    raise ValueError(msg)
ValueError: no signature found for builtin function <built-in function issubclass>
```

**Comment by smarie** [comment]
ok I saw in the doc that this might be normal.
